export enum NotificationType {
  // Booking notifications
  BOOKING_CREATED = 'BOOKING_CREATED',
  BOOKING_ASSIGNED = 'BOOKING_ASSIGNED',
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_COMPLETED = 'BOOKING_COMPLETED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',

  // Payment notifications
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_FAILED = 'PAYMENT_FAILED',

  // SOS notifications
  SOS_ALERT = 'SOS_ALERT',
  SOS_RESOLVED = 'SOS_RESOLVED',

  // System notifications
  SYSTEM = 'SYSTEM',
  GENERAL = 'GENERAL',
}
